// GENERATED by scripts/build-demo-set.mjs — do not edit by hand.
// The frozen demo set (T111 §5.1.1): 5 brands x 2 models x 2 generations
// x 2 variants = 40 variants, covering 10 of the 10 fuel types.
//
// FROZEN ON PURPOSE. Reading the set from the database at runtime would let it
// widen silently at the next import; the demo's whole guarantee is that it is
// the same 40 cars no matter how many demo keys exist.
//
// These are internal public_id values. They are never served: the API hands out
// opaque tokens (lib/public-id.ts) and this file is server-side only.
// Regenerate with: node scripts/build-demo-set.mjs --write
// Generated 2026-10-06 from the local cars_v3 replica.

export const DEMO_VARIANT_IDS: ReadonlySet<number> = new Set([
  30176,
  30178,
  30602,
  30605,
  32975,
  32977,
  37736,
  39755,
  39757,
  40389,
  40396,
  42825,
  52287,
  52323,
  65192,
  65194,
  74908,
  88138,
  90945,
  92789,
  92793,
  94747,
  94750,
  96782,
  104482,
  104486,
  105887,
  105900,
  107180,
  107183,
  108353,
  108360,
  109132,
  109134,
  111531,
  111532,
  111599,
  111600,
  112638,
  112639,
]);

export const DEMO_GENERATION_IDS: ReadonlySet<number> = new Set([
  3496,
  3530,
  3602,
  3603,
  4415,
  4435,
  4499,
  4505,
  4847,
  4848,
  4884,
  4888,
  7714,
  7761,
  7839,
  7847,
  7976,
  7986,
  8143,
  8149,
]);

export const DEMO_MODEL_IDS: ReadonlySet<number> = new Set([
  2151,
  2174,
  2438,
  2446,
  2531,
  2541,
  3208,
  3218,
  3263,
  3267,
]);

/** What the set contains, by name — safe to print in a log or a report.
 *  The brands and models are a DECISION (T111 §5.1.1); only the ids are derived. */
export const DEMO_SET_DESCRIPTION = "Volkswagen: Golf, Transporter · BMW: 3-serie, i3 · Toyota: Corolla, Prius · Hyundai: Tucson, Nexo · Ford: Focus, Mustang";

/** How many variants the set must contain. Asserted by the guard. */
export const DEMO_SET_SIZE = 40;

/** Readiness is DERIVED from the set, not declared beside it: a boolean next to
 *  the data is one more thing that can disagree with it. routes/demo.ts refuses
 *  to serve anything until these match, so an ungenerated or truncated set
 *  fails rather than quietly serving an empty catalogue. */
export const demoSetReady = (): boolean => DEMO_VARIANT_IDS.size === DEMO_SET_SIZE;
